// DECA events and their career clusters (copied from the main site js/events.js).
// Keep in sync with docs/js/events.js.
module.exports = [
  {"code":"ACT","event":"Accounting Applications","cluster":"Finance","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/accounting-applications-series"},
  {"code":"AAM","event":"Apparel and Accessories Marketing","cluster":"Marketing","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/apparel-and-accessories-marketing-series"},
  {"code":"ASM","event":"Automotive Services Marketing","cluster":"Marketing","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/automotive-services-marketing-series"},
  {"code":"BFS","event":"Business Finance","cluster":"Finance","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/business-finance-series"},
  {"code":"EBG","event":"Business Growth Plan","cluster":"Entrepreneurship","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/business-growth-plan"},
  {"code":"BLTDM","event":"Business Law and Ethics Team","cluster":"Business Management and Administration","type":"Role Play","competitors":"2","url":"https://www.deca.org/compete/business-law-and-ethics-team-decision-making"},
  {"code":"BSM","event":"Business Services Marketing","cluster":"Marketing","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/business-services-marketing-series"},
  {"code":"BOR","event":"Business Services Operations","cluster":"Business Management and Administration","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/business-services-operations-research"},
  {"code":"PMBS","event":"Business Solutions Project","cluster":"Business Management and Administration","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/business-solutions-project"},
  {"code":"BMOR","event":"Buying and Merchandising Operations","cluster":"Marketing","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/buying-and-merchandising-operations-research"},
  {"code":"BTDM","event":"Buying and Merchandising Team","cluster":"Marketing","type":"Role Play","competitors":"2","url":"https://www.deca.org/compete/buying-and-merchandising-team-decision-making"},
  {"code":"PMCD","event":"Career Development Project","cluster":"Business Management and Administration","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/career-development-project"},
  {"code":"PMCA","event":"Community Awareness Project","cluster":"Business Management and Administration","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/community-awareness-project"},
  {"code":"PMCG","event":"Community Giving Project","cluster":"Business Management and Administration","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/community-giving-project"},
  {"code":"ENT","event":"Entrepreneurship","cluster":"Entrepreneurship","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/entrepreneurship-series"},
  {"code":"ETDM","event":"Entrepreneurship Team","cluster":"Entrepreneurship","type":"Role Play","competitors":"2","url":"https://www.deca.org/compete/entrepreneurship-team-decision-making"},
  {"code":"FOR","event":"Finance Operations","cluster":"Finance","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/finance-operations-research"},
  {"code":"FCE","event":"Financial Consulting","cluster":"Finance","type":"Prepared","competitors":"1","url":"https://www.deca.org/compete/financial-consulting"},
  {"code":"PMFL","event":"Financial Literacy Project","cluster":"Business Management and Administration","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/financial-literacy-project"},
  {"code":"FTDM","event":"Financial Services Team","cluster":"Finance","type":"Role Play","competitors":"2","url":"https://www.deca.org/compete/financial-services-team-decision-making"},
  {"code":"FMS","event":"Food Marketing","cluster":"Marketing","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/food-marketing-series"},
  {"code":"EFB","event":"Franchise Business Plan","cluster":"Entrepreneurship","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/franchise-business-plan"},
  {"code":"HTDM","event":"Hospitality Services Team","cluster":"Hospitality and Tourism","type":"Role Play","competitors":"2","url":"https://www.deca.org/compete/hospitality-services-team-decision-making"},
  {"code":"HTOR","event":"Hospitality and Tourism Operations","cluster":"Hospitality and Tourism","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/hospitality-and-tourism-operations-research"},
  {"code":"HTPS","event":"Hospitality and Tourism Professional Selling","cluster":"Hospitality and Tourism","type":"Prepared","competitors":"1","url":"https://www.deca.org/compete/hospitality-and-tourism-professional-selling"},
  {"code":"HLM","event":"Hotel and Lodging Management","cluster":"Hospitality and Tourism","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/hotel-and-lodging-management-series"},
  {"code":"HRM","event":"Human Resources Management","cluster":"Business Management and Administration","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/human-resources-management-series"},
  {"code":"EIB","event":"Independent Business Plan","cluster":"Entrepreneurship","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/independent-business-plan"},
  {"code":"EIP","event":"Innovation Plan","cluster":"Entrepreneurship","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/innovation-plan"},
  {"code":"IMCE","event":"Integrated Marketing Campaign- Event","cluster":"Marketing","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/integrated-marketing-campaign-event"},
  {"code":"IMCP","event":"Integrated Marketing Campaign- Product","cluster":"Marketing","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/integrated-marketing-campaign-product"},
  {"code":"IMCS","event":"Integrated Marketing Campaign- Service","cluster":"Marketing","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/integrated-marketing-campaign-service"},
  {"code":"IBP","event":"International Business Plan","cluster":"Entrepreneurship","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/international-business-plan"},
  {"code":"MCS","event":"Marketing Communications","cluster":"Marketing","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/marketing-communications-series"},
  {"code":"MTDM","event":"Marketing Management Team","cluster":"Marketing","type":"Role Play","competitors":"2","url":"https://www.deca.org/compete/marketing-management-team-decision-making"},
  {"code":"PFL","event":"Personal Financial Literacy","cluster":"Personal Financial Literacy","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/personal-financial-literacy"},
  {"code":"PBM","event":"Principles of Business Management and Administration","cluster":"Business Administration Core","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/principles-of-business-management-and-administration"},
  {"code":"PEN","event":"Principles of Entrepreneurship","cluster":"Business Administration Core","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/principles-of-entrepreneurship"},
  {"code":"PFN","event":"Principles of Finance","cluster":"Business Administration Core","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/principles-of-finance"},
  {"code":"PHT","event":"Principles of Hospitality and Tourism","cluster":"Business Administration Core","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/principles-of-hospitality"},
  {"code":"PMK","event":"Principles of Marketing","cluster":"Business Administration Core","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/principles-of-marketing"},
  {"code":"PSE","event":"Professional Selling","cluster":"Marketing","type":"Prepared","competitors":"1","url":"https://www.deca.org/compete/professional-selling"},
  {"code":"QSRM","event":"Quick Serve Restaurant Management","cluster":"Hospitality and Tourism","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/quick-serve-restaurant-management-series"},
  {"code":"RFSM","event":"Restaurant and Food Services Management","cluster":"Hospitality and Tourism","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/restaurant-and-food-service-management-series"},
  {"code":"RMS","event":"Retail Merchandising","cluster":"Marketing","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/retail-merchandising-series"},
  {"code":"PMSP","event":"Sales Project","cluster":"Business Management and Administration","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/sales-project"},
  {"code":"SEM","event":"Sports and Entertainment Marketing","cluster":"Marketing","type":"Role Play","competitors":"1","url":"https://www.deca.org/compete/sports-and-entertainment-marketing-series"},
  {"code":"SEOR","event":"Sports and Entertainment Marketing Operations","cluster":"Marketing","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/sports-and-entertainment-marketing-operations-research"},
  {"code":"STDM","event":"Sports and Entertainment Team","cluster":"Marketing","type":"Role Play","competitors":"2","url":"https://www.deca.org/compete/sports-and-entertainment-marketing-team-decision-making"},
  {"code":"ESB","event":"Start-up Business Plan","cluster":"Entrepreneurship","type":"Prepared","competitors":"1-3","url":"https://www.deca.org/compete/start-up-business-plan"},
  {"code":"SMG","event":"Stock Market Game","cluster":"Finance","type":"Virtual","competitors":"1-3","url":"https://www.deca.org/compete/stock-market-game"},
  {"code":"TTDM","event":"Travel and Tourism Team","cluster":"Hospitality and Tourism","type":"Role Play","competitors":"2","url":"https://www.deca.org/compete/travel-and-tourism-team-decision-making"},
  {"code":"VBCAC","event":"Virtual Business Challenge- Accounting","cluster":"Finance","type":"Virtual","competitors":"1-3","url":"https://www.deca.org/compete/virtual-business-challenge-accounting"},
  {"code":"VBCEN","event":"Virtual Business Challenge- Entrepreneurship","cluster":"Entrepreneurship","type":"Virtual","competitors":"1-3","url":"https://www.deca.org/compete/virtual-business-challenge-entrepreneurship"},
  {"code":"VBCFA","event":"Virtual Business Challenge- Fashion","cluster":"Marketing","type":"Virtual","competitors":"1-3","url":"https://www.deca.org/compete/virtual-business-challenge-fashion"},
  {"code":"VBCHM","event":"Virtual Business Challenge- Hotel Management","cluster":"Hospitality and Tourism","type":"Virtual","competitors":"1-3","url":"https://www.deca.org/compete/virtual-business-challenge-hotel-management"},
  {"code":"VBCPF","event":"Virtual Business Challenge- Personal Finance","cluster":"Personal Financial Literacy","type":"Virtual","competitors":"1-3","url":"https://www.deca.org/compete/virtual-business-challenge-personal-finance"},
  {"code":"VBCRS","event":"Virtual Business Challenge- Restaurant","cluster":"Hospitality and Tourism","type":"Virtual","competitors":"1-3","url":"https://www.deca.org/compete/virtual-business-challenge-restaurant"},
  {"code":"VBCRT","event":"Virtual Business Challenge- Retail","cluster":"Marketing","type":"Virtual","competitors":"1-3","url":"https://www.deca.org/compete/virtual-business-challenge-retail"},
  {"code":"VBCSP","event":"Virtual Business Challenge- Sports","cluster":"Marketing","type":"Virtual","competitors":"1-3","url":"https://www.deca.org/compete/virtual-business-challenge-sports"}
];
